### ISSUE TITLE
Rooms do not load

### ISSUE THREAD

**Issue by Semir1212** [humhub-contrib/jitsi-meet#30]
HH 1.11.1
Jitsi 1.1.4
Domain: meet.jit.si

Might be connected with the ability to use a 'Room Prefix'.

**Comment by luke-** [comment]
@yurabakhtin I could reproduce this. After setting the Room Prefix the room doesn't load anymore. Also when removing the prefix afterwards.

**Comment by yurabakhtin** [comment]
@luke- @Semir1212 Could you give me an example, what values you used?

For example, if I go to https://meet.jit.si/ and create a room with name `ybprefix_room1900`, so I have opened an URL `https://meet.jit.si/ybprefix_room1900` and see there room name as "Ybprefix Room 1900".
What values should I use on HumHub side: "Room Prefix" = "ybprefix_" and "Room Name" = "room1900"?

Thanks.

**Comment by luke-** [comment]
@yurabakhtin You can reproduce the error here: https://staff.humhub.org/

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub-contrib/jitsi-meet/pull/31.
Really the bug was also without "Room Prefix" even if record `roomPrefix` is deleted from db table `setting`.
I could catch the bug sometimes after page refreshing, i.e. sometimes it is loaded and sometimes is not.

I detected the problem was on the line https://github.com/humhub-contrib/jitsi-meet/pull/31/files#diff-ab21399f5a9467f083a07e5e111809d5bb3a719e2df8f331372dc983d917d2a3L82:

- `this.jitsiApi.executeCommand('displayName', this.options.userdisplayname);`.

I didn't find a reason to keep this code because don't find any effect, so it was just deleted.

**Comment by luke-** [comment]
@yurabakhtin Thanks.
Previously, the Humhub display name of the user was passed to Jitsi. Is this still the case or does it not work anymore?

**Comment by yurabakhtin** [comment]
@luke- I see my account name, I think the data is passed here https://github.com/humhub-contrib/jitsi-meet/blob/fix/30-rooms-not-load/resources/humhub.jitsiMeet.js#L63-L66:

```js
userInfo: {
    fullName: this.options.userdisplayname,
    displayName: this.options.userdisplayname,
},
```

![jitsi_user_name](https://user-images.githubusercontent.com/6995524/167064774-6f75ee01-ef4d-414e-80c1-95f708d17ae9.png)

**Comment by luke-** [comment]
@yurabakhtin Thanks!
